# Generated by Django 4.2.2 on 2023-07-13 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.medialibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlayerIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('media_library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.medialibrary')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_video_files', models.FileField(upload_to='')),
                ('video_player_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.videoplayerintegration')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailsTrailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', models.ImageField(upload_to='thumbnails/')),
                ('trailer_video', models.FileField(upload_to='trailers/')),
                ('media_library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.medialibrary')),
            ],
        ),
        migrations.CreateModel(
            name='SocialSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_platform', models.CharField(max_length=100)),
                ('media_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.medialibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('media_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.medialibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('average_rating', models.FloatField()),
                ('media_library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.medialibrary')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptiveBitrateStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_quality', models.CharField(max_length=100)),
                ('video_encoding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.videoencoding')),
            ],
        ),
    ]
