# Generated by Django 4.2.2 on 2023-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_medialibrary_created_at_medialibrary_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibrary',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
