# Generated by Django 4.2.2 on 2023-10-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinod_whatsapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupparticipant',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='group',
            name='save_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
