# Generated by Django 4.2.2 on 2023-10-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinod_whatsapp1', '0002_remove_groupparticipant_is_admin_group_save_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='save_count',
        ),
    ]
