# Generated by Django 4.2.2 on 2023-07-20 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vinod_whatsapp1.validation


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinod_whatsapp1', '0005_message_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=50, validators=[vinod_whatsapp1.validation.validate_language])),
                ('chat_wallpaper', models.ImageField(blank=True, null=True, upload_to='chat_wallpapers/')),
                ('app_theme', models.CharField(default='light', max_length=20, validators=[vinod_whatsapp1.validation.validate_app_theme])),
                ('privacy_enabled', models.BooleanField(default=True, validators=[vinod_whatsapp1.validation.validate_privacy_enabled])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
