# Generated by Django 4.2.2 on 2023-07-10 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_remove_like_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.storyhighlight')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.story')),
            ],
        ),
    ]
